const typeActions = {
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    TURN_ON: 'TURN_ON',
    TWIST_ARRAY: 'TWIST_ARRAY',
    CHANGE_STRING: 'CHANGE_STRING',
    CHANGE_LOADING: 'CHANGE_LOADING'
}

export default typeActions;